'''
with open(rosalind_subs.txt) as file:
  content = file.read()
content[0],content[1] = s,t
'''

s = 'CAGGACGTAGGACGTACGGAGGACGTGAGGACGTAGGACGTCTAGGACGTTTGGACGAGGACGTAATTCAGTTAGGACGTCGAGTCCAAGGACGTACATAGGACGTAGGACGTTGAGGACGTCTCTAGGACGTAGGACGTAAGGACGTAACGCAGGACGTGGGAGGACGTCATAGGACGTAGCTTACCGTGTAAGGACGTACATCAGGACGTCGGGAAAAGCAAGGGGAGGACGTGTTAGGACGTTATATCAGGACGTAGGACGTGCTAGAGGACGTTACGAATCTGTGGCACTCGGTAGGACGTAGGACGTAGGACGTTAGGACGTAGGACGTTACAGGACGTAAGGACGTGATCTAGGACGTAGGACGTAGCTTCGAGGACGTTTCAAGGACGTAAGGACGTGTAGGACGTAGGACGTAGAGGACGTCCCTAGGACGTAGGACGTCATCAGGACGTAGGACGTAGAAGGACGTCAGAGGACGTCGCAGGACGTAATGAAGGACGTATGAGGACGTTTGCAAGCTAGGACGTAGGACGTCTATCAGGACGTCGAAGGACGTAAAGGACGTCGAGGACGTATAGGACGTTGCCTTCCACTCAATAAGGACGTTCTTTGAGGACGTTGAGGACGTCCCTTTCGGTAGGACGTGTGTAGAGGACGTAGGACGTGCAGAAGGACGTAGGACGTCTTGCGAGAGGACGTAGGACGTTTAGGACGTCGTCCAATGAGTAGGACGTACCAGAGGACGTCAGGACGTAGGACGTACTAGGACGTGTCGTAAAGGACGTCACA'
t = 'AGGACGTAG'
# 2,4,10

def find_substring(string,substring):
    res = ''
    if substring in string:
        res = [i+1 for i in range(len(string)) if string.startswith(substring, i)]
    return res
    
find_substring(s,t)
